CREATE TABLE IF NOT EXISTS outlets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS wines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  producer TEXT,
  grapes TEXT,
  vintage TEXT,
  country TEXT,
  region TEXT,
  appellation TEXT,
  subregion TEXT,
  format TEXT,
  type TEXT,
  category TEXT,
  search_key TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS wine_outlets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wine_id BIGINT NOT NULL REFERENCES wines(id) ON DELETE CASCADE,
  outlet_id BIGINT NOT NULL REFERENCES outlets(id) ON DELETE CASCADE,
  location TEXT,
  price TEXT,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at TIMESTAMPTZ,
  UNIQUE(wine_id, outlet_id)
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'viewer',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
  token TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS import_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  outlet TEXT NOT NULL,
  filename TEXT,
  stored_path TEXT,
  imported_count INTEGER NOT NULL,
  user_id BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_wine_outlets_active ON wine_outlets(active);
CREATE INDEX IF NOT EXISTS idx_import_batches_created_at ON import_batches(created_at DESC);

INSERT INTO outlets(name)
VALUES ('SHIMA'), ('LLUM I SAL'), ('MEL'), ('CERCLE'), ('QUIOSC')
ON CONFLICT (name) DO NOTHING;
