from __future__ import annotations

import os
import sys
from pathlib import Path

import psycopg

import app


SCHEMA = """
CREATE TABLE IF NOT EXISTS outlets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS wines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  producer TEXT,
  grapes TEXT,
  vintage TEXT,
  country TEXT,
  region TEXT,
  appellation TEXT,
  subregion TEXT,
  format TEXT,
  type TEXT,
  category TEXT,
  search_key TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS wine_outlets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wine_id BIGINT NOT NULL REFERENCES wines(id) ON DELETE CASCADE,
  outlet_id BIGINT NOT NULL REFERENCES outlets(id) ON DELETE CASCADE,
  location TEXT,
  price TEXT,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at TIMESTAMPTZ,
  UNIQUE(wine_id, outlet_id)
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'viewer',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
  token TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS import_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  outlet TEXT NOT NULL,
  filename TEXT,
  stored_path TEXT,
  imported_count INTEGER NOT NULL,
  user_id BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_wine_outlets_active ON wine_outlets(active);
CREATE INDEX IF NOT EXISTS idx_wines_search_key ON wines(search_key);
CREATE INDEX IF NOT EXISTS idx_import_batches_created_at ON import_batches(created_at DESC);
"""


def require_database_url() -> str:
    database_url = os.environ.get("DATABASE_URL", "").strip()
    if not database_url:
        print("Falta DATABASE_URL", file=sys.stderr)
        raise SystemExit(1)
    return database_url


def setup_schema(conn: psycopg.Connection) -> None:
    conn.execute(SCHEMA)
    for outlet in app.OUTLETS:
        conn.execute("INSERT INTO outlets(name) VALUES (%s) ON CONFLICT (name) DO NOTHING", (outlet,))


def setup_admin(conn: psycopg.Connection) -> None:
    password = app.bootstrap_admin_password()
    conn.execute(
        """
        INSERT INTO users(username, password_hash, role, active, created_at)
        VALUES (%s, %s, 'admin', TRUE, %s)
        ON CONFLICT (username) DO NOTHING
        """,
        ("admin", app.hash_password(password), app.now_iso()),
    )


def import_records(conn: psycopg.Connection, records: list[dict[str, str]], outlet_name: str, filename: str) -> int:
    outlet_id = conn.execute("SELECT id FROM outlets WHERE name = %s", (outlet_name,)).fetchone()[0]
    conn.execute(
        "UPDATE wine_outlets SET active = FALSE, updated_at = %s WHERE outlet_id = %s",
        (app.now_iso(), outlet_id),
    )
    count = 0
    for record in records:
        key = app.record_key(record)
        if not key:
            continue
        row = conn.execute(
            """
            INSERT INTO wines(name, producer, grapes, vintage, country, region, appellation, subregion, format, type, category, search_key)
            VALUES (%(name)s, %(producer)s, %(grapes)s, %(vintage)s, %(country)s, %(region)s, %(appellation)s, %(subregion)s, %(format)s, %(type)s, %(category)s, %(search_key)s)
            ON CONFLICT (search_key) DO UPDATE SET
              name=EXCLUDED.name, producer=EXCLUDED.producer, grapes=EXCLUDED.grapes, vintage=EXCLUDED.vintage,
              country=EXCLUDED.country, region=EXCLUDED.region, appellation=EXCLUDED.appellation,
              subregion=EXCLUDED.subregion, format=EXCLUDED.format, type=EXCLUDED.type, category=EXCLUDED.category
            RETURNING id
            """,
            {**record, "search_key": key},
        ).fetchone()
        wine_id = row[0]
        conn.execute(
            """
            INSERT INTO wine_outlets(wine_id, outlet_id, location, price, active, updated_at)
            VALUES (%s, %s, %s, %s, TRUE, %s)
            ON CONFLICT (wine_id, outlet_id) DO UPDATE SET
              location=EXCLUDED.location, price=EXCLUDED.price, active=TRUE, updated_at=EXCLUDED.updated_at
            """,
            (wine_id, outlet_id, record["location"], record["price"], record["updated_at"]),
        )
        count += 1
    admin_id = conn.execute("SELECT id FROM users WHERE username = 'admin'").fetchone()[0]
    conn.execute(
        """
        INSERT INTO import_batches(outlet, filename, stored_path, imported_count, user_id, created_at)
        VALUES (%s, %s, %s, %s, %s, %s)
        """,
        (
            outlet_name,
            filename,
            f"imports/{outlet_name.replace(' ', '_')}/{filename}",
            count,
            admin_id,
            app.now_iso(),
        ),
    )
    return count


def main() -> None:
    database_url = require_database_url()
    source = Path(os.environ.get("WOS_SEED_XLSX", app.UPLOAD_XLSX))
    if not source.exists():
        print(f"No existe el Excel: {source}", file=sys.stderr)
        raise SystemExit(1)
    records = app.parse_workbook(source, "SHIMA")
    with psycopg.connect(database_url, autocommit=True) as conn:
        setup_schema(conn)
        setup_admin(conn)
        count = import_records(conn, records, "SHIMA", source.name)
        active = conn.execute("SELECT COUNT(*) FROM wine_outlets WHERE active = TRUE").fetchone()[0]
    print(f"imported={count}")
    print(f"active={active}")


if __name__ == "__main__":
    main()
